server:
  port: 8082
spring:
  application:
    name: customer
eureka: #eureka client config
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #default address