server:
  port: 8081
spring:
  application:
    name: catalog
#Config Server 연결
  cloud:
    config:
      uri: http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka: #eureka client config
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #default address

hystrix:
  command:
    default:  # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # default 1,000ms (feign 과 같이 사용 시 hystrix timeout 이 우선 적용
      circuitBreaker:
        requestVolumeThreshold: 1 #default 20
        errorThresholdPercentage: 50 #default 50

#feign config
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full




