server:
  port: 8081
spring:
  application:
    name: catalog
hystrix:
  command:
    default:  # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

