server:
  port: 8081
spring:
  application:
    name: catalog
hystrix:
  command:
    default:  # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # default 1,000ms
      circuitBreaker:
        requestVolumeThreshold: 1 #default 20
        errorThresholdPercentage: 50 #default 50

