server:
  port: 8081
spring:
  application:
    name: catalog
hystrix:
  command:
    default:  # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # default 1,000ms
      circuitBreaker:
        requestVolumeThreshold: 1 #default 20
        errorThresholdPercentage: 50 #default 50

management:
  endpoints:
    web:
      exposure:
        include: "*"

#ribbon
product:
  ribbon:
    listOfServers: localhost:8082, localhost:7777
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
eureka: #eureka client config
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #default address