server:
  port: 8888
spring:
  application:
    name:
      -templateSimple
      -templatePortal
      -templateEnterprise
  profiles:
    active: native
# 로컬 저장소 사용 시 설정
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configuration-repository/
# 원격 저장소 사용 시 설정(git)
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/kangbyounghoon/ibro-config.git
#          skip-ssl-validation: false